#!/bin/bash
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# 2010-06-06 Sebastian Rockel
# Convert a gpx to itn (TomTom) file

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
MAXPOINTS=45 # TOMTOM itn is max. 48
tmpFile="$1".tmp
outFile="$1".itn
#echo "IN: $1"
#echo "OUT: $outFile"

# Convert to route only gpx file
$GPSBABEL -r -t -i gpx,gpxver=1.1 -f "$1" \
  -x nuketypes,waypoints \
  -x transform,rte=trk,del \
  -o tomtom_itn -F "$tmpFile" || exit $EXITKO

# Convert route gpx to itn file
$GPSBABEL -r -i tomtom_itn -f "$tmpFile" \
  -x simplify,count=$MAXPOINTS \
  -o tomtom_itn -F "$outFile" || exit $EXITKO

rm -f "$tmpFile" || exit $EXITKO

exit $EXITOK
