#!/bin/bash
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# 2010-06-06 Sebastian Rockel
# Takes gpx files as argument and merge them to one output file.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
GPXSEGMENTS=$HOME'/bin/gpxTools/gpxSegments'
OUTDIR='/tmp'
babelInput=$OUTDIR'/gpsbabel.tmp'

outFile="$1.merge.gpx"
maxChar=125 # More lead to error in gpx file

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for i in $@ ; do
  title=$title" "`$GPXSEGMENTS "$i"`
  if [ `diff $i $i` ] ; then # exploit diff to assure filename has no spaces!
    filesArg=$filesArg" -f "$i
  else
    n=`echo $i | sed -e 's/ /_/g'`
    mv "$i" "$n"
    filesArg=$filesArg" -f "$n
  fi
done
IFS=$SAVEIFS

echo $title
echo $filesArg

[ `echo "$title" | wc -c` -lt $maxChar ] || title="Merged log"

#echo "IN: $filesArg"
#echo "OUT: $outFile"

$GPSBABEL -r -t -i gpx,gpxver=1.1 $filesArg \
  -x nuketypes,waypoints \
  -x transform,trk=rte,del \
  -x track,merge,title="$title" \
  -o gpx,gpxver=1.1 -o gpx -F "$outFile" || exit $EXITKO

  #-x track,merge,title='COMBINED_LOG' \

exit $EXITOK
