#!/bin/bash
# 2010-06-06 Sebastian Rockel
# Takes gpx files as argument and merge them to one output file.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
filesArg=`echo $@ | sed -e 's/ / -f /g'`
outFile=$1".merge.gpx"

#echo "IN: $filesArg"
#echo "OUT: $outFile"

$GPSBABEL -r -t -i gpx,gpxver=1.1 -f $filesArg \
  -x nuketypes,waypoints \
  -x transform,trk=rte,del \
  -x track,merge,title='COMBINED_LOG' \
  -o gpx,gpxver=1.1 -o gpx -F $outFile || exit $EXITKO

exit $EXITOK
