#!/usr/bin/perl
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# Looks for more than one route/track in .gpx file and output the names
#
# 2010-06-06 Sebastian Rockel
# Several Routes in 1 file are recognized.
#
use warnings;
use strict;

# Geo::Gpx is a Perl module to create and parse GPX files.
# For more information for use see 'perldoc Geo::Gpx'
use Geo::Gpx;

# Open GPX file
(@ARGV>0) || die "You have to specify a '.gpx' file as argument!";
while (my $fpath = shift ) {
  open (my $fh, '<', $fpath) || die "Cannot open file $fpath: $!";

# Parse GPX from file
  my $gpxin = Geo::Gpx->new( input => $fh );

  if ( $gpxin->routes() ) {
    my @routeArray=@{$gpxin->routes()};
    for (my $route=0; $route < @routeArray; $route++) {
      print $gpxin->routes()->[$route]->{'name'}." ";
    }
  }
  if ( $gpxin->tracks() ) {
    my @trackArray=@{$gpxin->tracks()};
    for (my $track=0; $track < @trackArray; $track++) {
      print $gpxin->tracks()->[$track]->{'name'}." ";
    }
  }
  close ($fh);
}
print "\n";

exit 0;
