#!/bin/bash
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# 2010-06-06 Sebastian Rockel
# Convert a itn (TomTom) to gpx file

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
outFile=$1.gpx
echo "IN: $1"
echo "OUT: $outFile"

# Convert to route only gpx file
$GPSBABEL -r -i tomtom_itn -f $1 \
  -o gpx,gpxver=1.1 -F $outFile || exit $EXITKO

exit $EXITOK
