#!/bin/bash
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# 2010-06-04 Sebastian Rockel
# Create a gpx copy of given file and reduce the # of route points to < 25.
# This is due to google maps limit of route points to alphabet letters
# Finally display the route via google maps.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
GPX2GMAP=$HOME'/bin/gpxTools/gpx2gmap'
OUTDIR='/tmp'
MAXPOINTS=24 # Google Maps has max. 24

# Replace spaces in file names with '_'
outFile=$OUTDIR/`basename -s .gpx "$1" | sed -e 's/ /_/g'`_asRoute.gpx
# TODO fix file with spaces

#echo "$1"
#echo "$outFile"

# Call gpsbabel
$GPSBABEL -r -t -i gpx,gpxver=1.1 -f "$1" \
  -x nuketypes,waypoints \
  -x transform,trk=rte,del \
  -x track,merge,title="COMBINED_LOG" \
  -x transform,rte=trk,del \
  -x simplify,count=$MAXPOINTS \
  -o gpx,gpxver=1.1 \
  -F "$outFile" || exit $EXITKO

# Call gpx (route) to google maps translator
$GPX2GMAP "$outFile" || exit $EXITKO

# Wait for the browser to be started
sleep 5
# Clean temporary files
rm -f $OUTDIR/`basename -s .gpx $outFile`*

exit $EXITOK
