#!/bin/bash
# 2010-06-04 Sebastian Rockel
# Create a gpx copy of given file and reduce the # of route points to < 25.
# This is due to google maps limit of route points to alphabet letters
# Finally display the route via google maps.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
BABELPATH='/opt/local/bin'
GPX2GMAP='/Users/sebastian/bin'
OUTDIR='/Users/sebastian/tmp'

# TODO Wordaround for Automator giving args twice in $@
#for f in "$@"
#do

  outFile=$OUTDIR/`basename -s .gpx $1`_asRoute.gpx

  # Call gpsbabel
  # TODO Why is count=8 equal to 3*8=24 route points?
  $BABELPATH/gpsbabel -r -t -i gpx,gpxver=1.1 -f $1 -x nuketypes,waypoints \
    -x transform,rte=trk,del -x simplify,count=8 -o gpx,gpxver=1.1 \
    -F $outFile || exit $EXITKO

  # Call gpx (route) to google maps translator
  $GPX2GMAP/gpx2gmap $outFile || exit $EXITKO

  # Wait for the browser to be started
  sleep 5
  # Clean temporary files
  rm -f $OUTDIR/`basename -s .gpx $outFile`*

#done

exit $EXITOK
