#!/bin/bash
#This work by Sebastian Rockel (sebastianrockel@gmail.com) is licensed under a 
#Creative Commons Attribution-Noncommercial-Share Alike 3.0 Germany License.
#"http://creativecommons.org/licenses/by-nc-sa/3.0/de/"
#
# 2010-06-04 Sebastian Rockel
# Create a gpx copy of given file and converts any route(s) to track(s).
# Finally display the track via google maps.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
GPX2MAP=$HOME'/bin/gpx2map/gpx2map'
BROWSER='open' # Put your browser command here
GPXSEGMENTS=$HOME'/bin/gpxTools/gpxSegments_new'
OUTDIR='/tmp'

# Replace spaces in file names with '_'
outFile=$OUTDIR/`basename -s .gpx "$1" | sed -e 's/ /_/g'`_asTrack.gpx
htmlFile=$OUTDIR/`basename -s .gpx "$outFile" | sed -e 's/ /_/g'`*.html
maxChar=125 # More lead to error in gpx file

# Call gpsbabel
$GPSBABEL -r -i gpx,gpxver=1.1 -f "$1" \
  -x nuketypes,waypoints \
  -x transform,trk=rte,del \
  -o gpx,gpxver=1.1 -F "$outFile" || exit $EXITKO

title=`$GPXSEGMENTS "$outFile"`
[ `echo "$title" | wc -c` -lt $maxChar ] || title="Merge of many tracks"

# Call gpx (track) to google maps translator
#Looks like gpx2map seg faults on large merged tracks from gpsbabel
#but not if it merges them self!?
$GPX2MAP --title "$title" --merge "$outFile" #|| exit $EXITKO

# Open browser and load map
$BROWSER $htmlFile || exit $EXITKO

# Wait for the browser to be started
sleep 2
# Clean temporary files
rm -f $OUTDIR/`basename -s .gpx $outFile`*

exit $EXITOK
