#!/bin/bash
# 2010-06-04 Sebastian Rockel
# Create a gpx copy of given file and converts any route(s) to track(s).
# Finally display the track via google maps.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
GPSBABEL='/opt/local/bin/gpsbabel'
GPX2MAP=$HOME'/bin/gpx2map/gpx2map'
BROWSER='open' # Put your browser command here
OUTDIR='/tmp'

outFile=$OUTDIR/`basename -s .gpx $1`_asTrack.gpx
htmlFile=$OUTDIR/`basename -s .gpx $outFile`*.html

# Call gpsbabel
$GPSBABEL -r -i gpx,gpxver=1.1 -f $1\
  -x nuketypes,waypoints \
  -x transform,trk=rte,del \
  -o gpx,gpxver=1.1 -F $outFile || exit $EXITKO

  #-x track,merge,title="COMBINED_LOG" \

# Call gpx (track) to google maps translator
#Looks like gpx2map seg faults on large merged tracks from gpsbabel
#but not if it merges them self!?
$GPX2MAP --merge $outFile || exit $EXITKO

# Open browser and load map
$BROWSER $htmlFile || exit $EXITKO

# Wait for the browser to be started
sleep 2
# Clean temporary files
rm -f $OUTDIR/`basename -s .gpx $outFile`*

exit $EXITOK
