#!/bin/bash
# 2010-06-04 Sebastian Rockel
# Create a gpx copy of given file and converts any route(s) to track(s).
# Finally display the track via google maps.

EXITKO=-1
EXITOK=0

[ $# -gt 0 ] || exit $EXITKO

# Script paths
BABELPATH='/opt/local/bin'
GPX2MAP='/Users/sebastian/bin/gpx2map'
OUTDIR='/Users/sebastian/tmp'

# TODO Wordaround for Automator giving args twice in $@
#touch $OUTDIR/viewAsTrack.log
#echo "$@" >> $OUTDIR/viewAsTrack.log

#for f in "$@"
#while [ $# -gt 0 ]
#do

  outFile=$OUTDIR/`basename -s .gpx $1`_asTrack.gpx
  htmlFile=$OUTDIR/`basename -s .gpx $outFile`*.html

  # Call gpsbabel
  $BABELPATH/gpsbabel -r -i gpx,gpxver=1.1 -f $1\
    -x nuketypes,waypoints \
    -x transform,trk=rte,del \
    -o gpx,gpxver=1.1 -F $outFile || exit $EXITKO

  # Call gpx (track) to google maps translator
  $GPX2MAP/gpx2map --merge $outFile || exit $EXITKO

  # Open browser and load map
  open $htmlFile || exit $EXITKO

  # Wait for the browser to be started
  sleep 5
  # Clean temporary files
  rm -f $OUTDIR/`basename -s .gpx $outFile`*

  #shift 2
#done

exit $EXITOK
