#!/bin/bash
# 2010-03-16 Sebastian Rockel
# Ping  hosts to check they are alive and reachable
# Check shall be as light as possible

ptimeout=1 # ping timeout in seconds
plogfile="$HOME/`basename $0`_log.txt"
E_OK=0
E_NOK=1
E_NORESP=2 # ping exit for no response
E_NOHOST=68 # ping exit for unknown host

if [ ! -z $1 ] ; then
  HLIST=$1 # List of hosts to check
else
  echo; echo "Give a file with hosts: `basename $0` <hostsfile>"; echo
  exit $E_NOK;
fi

echo >> $plogfile 
echo "=== START SESSION `date` ===" >>$plogfile # Mark a new session

for host in `cat $HLIST | sed -e 's/#.*//'`; do
  echo >> $plogfile
  ping -n -o -t $ptimeout $host >>$plogfile 2>&1 
  case $? in
    $E_OK)      echo "$host is ALIVE";;
    $E_NORESP)  echo "$host does not respond";;
    $E_NOHOST)  echo "$host is unknown";;
    *)          echo "Unknown error, see logfile $plogfile";;
  esac
done

echo; echo "Written logfile to $plogfile"; echo

exit $E_OK
