#!/bin/sh
#
# usefule find grep!
if [ $# -lt 2 ]
then
   echo
   echo "Usage: cp2fh <file(s)> <remote dir>"
   echo "remote dir starts at home: ~/<further dirs>"
   echo
   exit
else
   scp $1 in17284@141.75.164.133:~/$2
fi

