#!/opt/local/bin/perl -w

@sachen=("iPod",
         "iPod-Datenkabel",
         "iBook",
         "iBook-Stromkabel",
         "iBooktasche",
         "Lohnsteuerkarte",
         "Steuerbelege",
         "Studiengebühren (Kto.auszüge)",
         "Fachmagazine (Kto.auszüge)",
         "Portemonaie",
         "Ausweise",
         "Führerschein",
         "Autoschlüssel",
         "Türschlüssel(LUI)",
         "Wäsche",
         "Slips",
         "Strümpfe",
         "Hemd(en)",
         "Schuhe",
         "Jacke"
);
format STDOUT = 
@>>/@<)  @<<<<<<<<<<<<<<<<<<<<<<<<<<<< (y/n)
$j, $num, $_               
.
# Formatkopf:
format STDOUT_TOP =

               HEIMFAHRT  
   -----------------------------------
Dran gedacht?

.
$num=$#sachen + 1; 
$i=0;
foreach (@sachen) {
   $i++; $j="(".$i;
   write;
   chomp($input=<>);
   if ($input eq "n"){ exit 1; }
}

exit 0;
