#!/usr/bin/perl -w
# http://blog.dinotools.de/2008/11/24/einzelne-tracks-aus-gpx-dateien-extrahieren
 
$file = $ARGV[0];
$tmp_file = "$file.tmp";
print "Setting track names ... ";
system("gpsbabel -t -r -w -i gpx -f $file -x track,title='track-%Y%m%d-%H%M%S' -o gpx -F $tmp_file");
print "done\n";
print "Getting track names ... ";
open(INFILE, $tmp_file);
@tracks = ();
while($line = &lt;INFILE&gt;) {
        if($line =~ m/ *&lt;name&gt;(track-[0-9-]*)&lt;\/name&gt;/i) {
                push(@tracks, $1);
        }
}
close(INFILE);
print "done\n";
$count = 1;
$num = @tracks;
print "Tracks found: $num\n";
print "Extracting tracks ... \n";
foreach(@tracks) {
        system("gpsbabel -t -r -w -i gpx -f $tmp_file -x track,name='$_' -o gpx -F $_.gpx");
        print "Track $count from $num\n";
        $count++;
}
print "done\n";
