#!/usr/bin/perl

use warnings;
use strict;
use Time::Local;

my @tablerow;
my @tmp;
my $index = 0;
my $magicflag = 0x0;

# expected format: '03.10.2001'
sub dayofweek {

  my $searchDate = shift @_;
  my @days=('So','Mo','Di','Mi','Do','Fr','Sa');
  my ($day,$month,$year) = split(/\./,$searchDate);
  my $wday = @days[(localtime(timelocal(0,0,0,$day,$month-1,$year-1900)))[6]];

  return $wday;
}

if ( ! $ARGV[0]){
  die "No argument given!\n";
}

my $file_raw = shift @ARGV;
my $file_list = $file_raw.".list";

open(FILE_RAW, "<", $file_raw) or die "Couldn't open $file_raw: $!\n";
open(FILE_LIST, ">", $file_list) or die "Couldn't create $file_list: $!\n";


while(<FILE_RAW>){
  if(/Lotto-Ziehung vom\D*((\d|\.)+).+/){
    if(($magicflag & 0b00000011) == 0b00000011){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    push(@tablerow, dayofweek($tablerow[0]));
    $magicflag |= 0b00000011;

  } elsif(/^Gewinnzahlen:\D*((\d|\s|\,)+)/){
    if(($magicflag & 0b00000100) == 0b00000100){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    $magicflag |= 0b00000100;

  } elsif(/^Zusatzzahl:\D*(\d+)/){
    if(($magicflag & 0b00001000) == 0b00001000){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    $magicflag |= 0b00001000;

  } elsif(/^Superzahl:\D*(\d+)/){
    if(($magicflag & 0b00010000) == 0b00010000){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    $magicflag |= 0b00010000;

  } elsif(/^Spiel 77:\D*(\d+)/){
    if(($magicflag & 0b00100000) == 0b00100000){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    $magicflag |= 0b00100000;

  } elsif(/^Super 6:\D*(\d+)/){
    if(($magicflag & 0b01000000) == 0b01000000){
      die "Error in file structure at: '$_'!\n";
    }
    chomp(my $tmp = $1);
    push(@tablerow, $tmp);
    $magicflag |= 0b01000000;

  };
  if(($magicflag & 0b01111111) == 0b01111111){

    # Reset magic counter
    $magicflag = 0x0;

    print FILE_LIST join(" | ",
      reverse(split(/\./, shift(@tablerow))),
      shift(@tablerow),
      split(/\,/, shift(@tablerow)),
      shift(@tablerow),
      shift(@tablerow),
      shift(@tablerow),
      shift(@tablerow)                )."\n";

    # Increase table row
    $index++;
  }
}

print "Successfully parsed $index datasets\n";

close(FILE_RAW);
close(FILE_LIST);

exit 0;
